### ISSUE TITLE
huge mistake spoted 

### ISSUE THREAD

**Issue by Jocho-Smith** [ThomasJon196/Kekukleks#1]
Ich glaube da fehlt ein Punkt

**Comment by Jocho-Smith** [comment]
Und lasst mal nen VPN einrichten zum RPi. Will endlich eure klo-sounds.

**Comment by ThomasJon196** [comment]
> Ich glaube da fehlt ein Punkt

.

**Comment by ThomasJon196** [comment]
> Und lasst mal nen VPN einrichten zum RPi. Will endlich eure klo-sounds.

Schonmal gemacht?

**Comment by Jocho-Smith** [comment]
> > Und lasst mal nen VPN einrichten zum RPi. Will endlich eure klo-sounds.
> 
> Schonmal gemacht?

Nö aber du hast ja jetzt Zeit ;)
Tipp:
https://openvpn.net/community-resources/how-to/

**Comment by Jocho-Smith** [comment]
~closed
